CREATE TABLE `contratos` (
  `contratoId` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de el contrato como contador autoincremental',
  `tipocontratoId` int(11) NOT NULL COMMENT 'Tipo de el contrato = tipo mantenimiento',
  `referencia` varchar(255) NOT NULL COMMENT 'Referencia de el contrato pa5ra búsquedas',
  `empresaId` int(11) NOT NULL COMMENT 'Empresa propia que realiza el contrato',
  `clienteId` int(11) NOT NULL COMMENT 'Cliente final al que va dirigida el contrato',
  `mantenedorId` int(11) DEFAULT NULL COMMENT 'Mantenedor (si es que lo hay) que media en el contrato',
  `agenteId` int(11) DEFAULT NULL COMMENT 'Agente (comerciales) que se asocia a el contrato',
  `fechacontrato` date NOT NULL COMMENT 'Fecha de creación de el contrato',
  `coste` decimal(12,2) NOT NULL COMMENT 'Coste global de el contrato',
  `porcentajeBeneficio` decimal(5,2) NOT NULL COMMENT '% sobre el coste para calcular beneficio',
  `importeBeneficio` decimal(12,2) NOT NULL COMMENT 'Importe del beneficio',
  `ventaNeta` decimal(12,2) NOT NULL COMMENT 'Coste + Beneficio',
  `porcentajeAgente` decimal(5,2) DEFAULT NULL COMMENT 'Porcentaje de comision del agente (sobre importeCliente)',
  `importeAgente` decimal(12,2) DEFAULT NULL COMMENT 'Importe del agente',
  `importeCliente` decimal(12,2) NOT NULL COMMENT 'VentaNeta + ImporteAgente',
  `importeMantenedor` decimal(12,2) DEFAULT NULL COMMENT 'ImporteMantenedor = ImporteCliente - VentaNeta + beneficio',
  `observaciones` text,
  `formaPagoId` int(11) DEFAULT NULL,
  `total` decimal(12,2) DEFAULT NULL,
  `totalConIva` decimal(12,2) DEFAULT NULL,
  PRIMARY KEY (`contratoId`),
  KEY `cnt_tipoMantenimiento` (`tipocontratoId`),
  KEY `cnt_empresa` (`empresaId`),
  KEY `cnt_cliente` (`clienteId`),
  KEY `cnt_mantenedor` (`mantenedorId`),
  KEY `cnt_agente` (`agenteId`),
  KEY `cnt_formaPago` (`formaPagoId`),
  CONSTRAINT `cnt_agente` FOREIGN KEY (`agenteId`) REFERENCES `comerciales` (`comercialId`),
  CONSTRAINT `cnt_cliente` FOREIGN KEY (`clienteId`) REFERENCES `clientes` (`clienteId`),
  CONSTRAINT `cnt_empresa` FOREIGN KEY (`empresaId`) REFERENCES `empresas` (`empresaId`),
  CONSTRAINT `cnt_formaPago` FOREIGN KEY (`formaPagoId`) REFERENCES `formas_pago` (`formaPagoId`),
  CONSTRAINT `cnt_mantenedor` FOREIGN KEY (`mantenedorId`) REFERENCES `clientes` (`clienteId`),
  CONSTRAINT `cnt_tipoMantenimiento` FOREIGN KEY (`tipocontratoId`) REFERENCES `tipos_mantenimiento` (`tipoMantenimientoId`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

CREATE TABLE `contratos_bases` (
  `contratoBaseId` int(11) NOT NULL AUTO_INCREMENT,
  `contratoId` int(11) DEFAULT NULL,
  `tipoIvaId` int(11) DEFAULT NULL,
  `porcentaje` decimal(5,2) DEFAULT NULL,
  `base` decimal(12,2) DEFAULT NULL,
  `cuota` decimal(12,2) DEFAULT NULL,
  PRIMARY KEY (`contratoBaseId`),
  UNIQUE KEY `cntb_prefac_iva` (`contratoId`,`tipoIvaId`),
  KEY `cntb_tipos_iva` (`tipoIvaId`),
  CONSTRAINT `cntb_contratos` FOREIGN KEY (`contratoId`) REFERENCES `contratos` (`contratoId`) ON DELETE CASCADE,
  CONSTRAINT `cntb_tipos_iva` FOREIGN KEY (`tipoIvaId`) REFERENCES `tipos_iva` (`tipoIvaId`)
) ENGINE=InnoDB AUTO_INCREMENT=252 DEFAULT CHARSET=utf8;

CREATE TABLE `contratos_lineas` (
  `contratoLineaId` int(11) NOT NULL AUTO_INCREMENT,
  `linea` decimal(6,3) DEFAULT NULL,
  `contratoId` int(11) DEFAULT NULL,
  `articuloId` int(11) DEFAULT NULL,
  `tipoIvaId` int(11) DEFAULT NULL,
  `porcentaje` decimal(5,2) DEFAULT NULL,
  `descripcion` text,
  `cantidad` decimal(6,2) DEFAULT NULL,
  `importe` decimal(10,2) DEFAULT NULL,
  `totalLinea` decimal(12,2) DEFAULT NULL,
  `coste` decimal(12,2) DEFAULT NULL,
  `porcentajeBeneficio` decimal(5,2) DEFAULT NULL,
  `porcentajeAgente` decimal(5,2) DEFAULT NULL,
  `capituloLinea` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`contratoLineaId`),
  KEY `cntl_contratos` (`contratoId`),
  KEY `cntl_articulos` (`articuloId`),
  KEY `cntl_tipos_iva` (`tipoIvaId`),
  CONSTRAINT `cntl_articulos` FOREIGN KEY (`articuloId`) REFERENCES `articulos` (`articuloId`),
  CONSTRAINT `cntl_contratos` FOREIGN KEY (`contratoId`) REFERENCES `contratos` (`contratoId`) ON DELETE CASCADE,
  CONSTRAINT `cntl_tipos_iva` FOREIGN KEY (`tipoIvaId`) REFERENCES `tipos_iva` (`tipoIvaId`)
) ENGINE=InnoDB AUTO_INCREMENT=188 DEFAULT CHARSET=utf8;