CREATE TABLE `audit_facturas` (
  `auditFacturasId` INT(11) NOT NULL AUTO_INCREMENT,
  `facturaId` INT(11) NOT NULL,
  `numFactu` VARCHAR(255) NOT NULL,
  `tipo` ENUM('NEW','EDIT','DELETE') NOT NULL,
  `procesado` TINYINT(1) NOT NULL DEFAULT '0',
  `cambio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`auditFacturasId`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `audit_facproves` (
  `auditFacprovesId` INT(11) NOT NULL AUTO_INCREMENT,
  `facproveId` INT(11) NOT NULL,
  `numFactu` VARCHAR(255) NOT NULL,
  `tipo` ENUM('NEW','EDIT','DELETE') NOT NULL,
  `procesado` TINYINT(1) NOT NULL DEFAULT '0',
  `cambio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`auditFacprovesId`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

