#TABLAS TEMPORALES PARA EL INFORME DE COBROS REPERCUTIDOS Y GESTIONADOS DE LOS CONTRATOS

CREATE TABLE `tmp_contratos` (
  `contratoId` int(11) NOT NULL default '0' COMMENT 'Identificador único de el contrato como contador autoincremental',
  `referencia` varchar(255) character set utf8 NOT NULL COMMENT 'Referencia de el contrato pa5ra búsquedas',
  `fechaInicio` varchar(255) default NULL,
  `fechaFinal` varchar(255) default NULL,
  `fechaFirmaActa` varchar(255) default NULL,
  `certificacionFinal` decimal(12,2) default NULL,
  `certificacionFinalIva` decimal(12,2) default NULL,
  `total` decimal(12,2) default NULL,
  `totalConIva` decimal(12,2) default NULL,
  `coste` decimal(14,4) NOT NULL default '0.0000',
  `BI` decimal(15,4) default NULL,
  `porBI` decimal(19,8) default NULL,
  `BINeto` decimal(20,4) default NULL,
  `empresaId` int(11) default '0',
  `nombreEmpresa` varchar(255) character set utf8 default NULL,
  `clienteId` int(11) default '0',
  `clienteNombre` varchar(255) character set utf8 default NULL,
  `agenteId` int(11) default '0',
  `agenteNombre` varchar(255) character set utf8 default NULL,
  `importeAgente` decimal(12,2) default NULL,
  `comercialId` int(11) default '0',
  `comercialNombre` varchar(255) character set utf8 default NULL,
  `importeComercial` decimal(13,2) default NULL,
  `jGrupoId` int(11) default '0',
  `jGrupoNombre` varchar(255) character set utf8 default NULL,
  `importejefeGrupo` decimal(13,2) default NULL,
  `jObrasId` int(11) default '0',
  `jObrasNombre` varchar(255) character set utf8 default NULL,
  `importejefeObras` decimal(13,2) default NULL,
  `arquitectoId` int(11) default '0',
  `arquitectoNombre` varchar(255) character set utf8 default NULL,
  `importeArquitecto` decimal(13,2) default NULL,
  `recepcionActa` varchar(2) character set utf8 NOT NULL default '',
  `tieneCertFinal` varchar(2) character set utf8 NOT NULL default '',
  `contratoCerrado` varchar(2) character set utf8 NOT NULL default '',
  `usuarioId` int(1) NOT NULL default '0',
  PRIMARY KEY  (`contratoId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;



CREATE TABLE `tmp_cobros` (
  `contratoId` int(11) NOT NULL default '0',
  `numserie` char(3) NOT NULL,
  `numfactu` int(11) NOT NULL default '0',
  `fecfactu` date NOT NULL default '0000-00-00',
  `numorden` smallint(1) unsigned NOT NULL default '0',
  `codmacta` varchar(10) NOT NULL default '',
  `codforpa` smallint(6) NOT NULL default '0',
  `fecvenci` date NOT NULL default '0000-00-00',
  `impvenci` decimal(12,2) NOT NULL default '0.00',
  `ctabanc1` varchar(10) NOT NULL default '',
  `iban` varchar(40) default NULL,
  `fecultco` date default NULL,
  `impcobro` decimal(12,2) default NULL,
  `emitdocum` tinyint(3) unsigned NOT NULL default '0',
  `recedocu` tinyint(3) unsigned NOT NULL default '0',
  `contdocu` tinyint(3) unsigned NOT NULL default '0',
  `text33csb` varchar(80) default NULL,
  `text41csb` varchar(60) default NULL,
  `ultimareclamacion` date default NULL,
  `agente` smallint(5) unsigned default NULL,
  `departamento` smallint(3) unsigned default NULL,
  `tiporem` tinyint(4) default NULL,
  `codrem` smallint(3) unsigned default NULL,
  `anyorem` smallint(4) default NULL,
  `siturem` char(1) default NULL,
  `gastos` decimal(10,2) default NULL,
  `Devuelto` tinyint(4) default '0',
  `situacionjuri` tinyint(3) unsigned default '0',
  `noremesar` tinyint(3) unsigned NOT NULL default '0',
  `observa` text,
  `Transfer` int(11) default NULL,
  `referencia` varchar(15) default NULL,
  `referencia1` varchar(15) default NULL,
  `referencia2` varchar(15) default NULL,
  `nomclien` varchar(60) default NULL COMMENT 'Nombre cliente',
  `domclien` varchar(60) default NULL COMMENT 'domicilio',
  `pobclien` varchar(60) default NULL COMMENT 'poblacion',
  `cpclien` varchar(6) default NULL COMMENT 'codigo postal',
  `proclien` varchar(60) default NULL COMMENT 'provincia',
  `feccomunica` date default NULL COMMENT 'Fecha comunicacion',
  `fecprorroga` date default NULL COMMENT 'Fecha prorroga',
  `fecsiniestro` date default NULL COMMENT 'Fecha aviso siniestro',
  `fecejecutiva` date default NULL COMMENT 'Recaudacion ejecutiva',
  `nifclien` varchar(15) default NULL,
  `codpais` char(2) default NULL,
  `situacion` tinyint(1) default '0' COMMENT '0=pendiente cobro 1=cobrado',
  `codusu` int(7) default NULL,
  `comunicadoServer` tinyint(4) default '0' COMMENT 'TrasBOLBAITE',
  `reciboanticipado` tinyint(4) default '0' COMMENT 'Cobro anticipado',
  `nomforpa` varchar(40),
  `esSeguro` int(2) NOT NULL default '0',
  `usuarioId` int(1) NOT NULL default '0',
  KEY `keyContrato` (`contratoId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

