CREATE TABLE `facturas` (
  `facturaId` INT(11) NOT NULL AUTO_INCREMENT,
  `ano` INT(11) DEFAULT NULL,
  `numero` INT(11) DEFAULT NULL,
  `serie` VARCHAR(255) DEFAULT NULL,
  `fecha` DATE DEFAULT NULL,
  `empresaId` INT(11) DEFAULT NULL,
  `clienteId` INT(11) DEFAULT NULL,
  `contratoClienteMantenimientoId` INT(11) DEFAULT NULL,
  `emisorNif` VARCHAR(255) DEFAULT NULL,
  `emisorNombre` VARCHAR(255) DEFAULT NULL,
  `emisorDireccion` VARCHAR(255) DEFAULT NULL,
  `emisorCodPostal` VARCHAR(255) DEFAULT NULL,
  `emisorPoblacion` VARCHAR(255) DEFAULT NULL,
  `emisorProvincia` VARCHAR(255) DEFAULT NULL,
  `receptorNif` VARCHAR(255) DEFAULT NULL,
  `receptorNombre` VARCHAR(255) DEFAULT NULL,
  `receptorDireccion` VARCHAR(255) DEFAULT NULL,
  `receptorCodPostal` VARCHAR(255) DEFAULT NULL,
  `receptorPoblacion` VARCHAR(255) DEFAULT NULL,
  `receptorProvincia` VARCHAR(255) DEFAULT NULL,
  `total` DECIMAL(12,2) DEFAULT NULL,
  `totalConIva` DECIMAL(12,2) DEFAULT NULL,
  `formaPagoId` INT(11) DEFAULT NULL,
  `observaciones` TEXT,
  `sel` TINYINT(1) DEFAULT '0',
  PRIMARY KEY (`facturaId`),
  KEY `fact_empresas` (`empresaId`),
  KEY `fact_clientes` (`clienteId`),
  KEY `fact_formas_pago` (`formaPagoId`),
  KEY `fact_contratos` (`contratoClienteMantenimientoId`),
  CONSTRAINT `fact_clientes` FOREIGN KEY (`clienteId`) REFERENCES `clientes` (`clienteId`),
  CONSTRAINT `fact_contratos` FOREIGN KEY (`contratoClienteMantenimientoId`) REFERENCES `contrato_cliente_mantenimiento` (`contratoClienteMantenimientoId`),
  CONSTRAINT `fact_empresas` FOREIGN KEY (`empresaId`) REFERENCES `empresas` (`empresaId`),
  CONSTRAINT `fact_formas_pago` FOREIGN KEY (`formaPagoId`) REFERENCES `formas_pago` (`formaPagoId`)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

