INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('27',42,'Solado/terrazo (raseado arena/cemento)',0,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('28',42,'Picar hormigon',23.21,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('29',42,'Tapado de cala con hormigon 1m2.',76.79,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('30',42,'Adicional de tapar cala con hormigon',49.91,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('31',42,'Reparar filtraciones',0,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('32',42,'Suministro y colocacion de amstrong',0,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('33',42,'Solado de terrazo',0,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('201',42,'Tapado de cala con enlucido 1 o 2 caras 1m2.',131.5,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('202',42,'Tapado de 1m2 de cala en techo de escayola.',117.85,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('203',42,'Tapado de 1m2 de cala con alicatado o solado a 1 cara.',143.89,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('204',42,'Tapado de 1/2m2 de cala con enlucido 1 o 2 caras.',89.14,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('205',42,'Tapado de 1/2m2 de cala en techo de escayola.',103.19,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('206',42,'Tapado de 1/2m2 de cala con alicatado o solado a 1cara.',104.28,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('207',42,'Tabicado incluso raseado de cemento hasta 1/2m2.',78.85,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('208',42,'Tabicado incluso raseado de cemento hasta 1m2.',122.81,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('209',42,'Reconstruccion de mocheta hasta 1m, acabada en yeso.',115.37,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('210',42,'Reconstruccion de mocheta hasta 2,5m, acabada en yeso.',200.98,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('211',42,'Picado de yeso.',14.88,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('212',42,'Picado de mortero de cemento.',23.2,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('213',42,'Tendido de yeso negro.',20.47,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('214',42,'Enlucido de yeso blanco.',16.66,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('215',42,'Falso techo de escayola, m2 adicional.',42.16,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('216',42,'Moldura de escayola.',21.1,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('217',42,'Alicatado o solado.',72.68,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('218',42,'Alicatado o solado, para superficie mayor de 3m2.',55.98,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('219',42,'Tabicado de pared, m2 adicional.',44.67,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('220',42,'Enfoscado de mortero de cemento.',27.31,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('221',42,'Mano de obra albañilería',43.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1401',43,'Apertura de puerta',124.57,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1402',43,'Sustitución de bombin normal (Tipo CVL, EZCUR, TESA, AZBE o similar)',110.67,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1403',43,'Sustituc. bombillo seguridad, pompa o borjas g. baja (EZCURRA,ESA)',159.59,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1404',43,'Sustituc. bombillo seguridad,pompa o borjas g. media (EZCURRA,ESA)',228.64,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1405',43,'Sustituc. bombillo seguridad,pompa o borjas g. alta (EZCURRA,ESA)',240.32,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1406',43,'Sust.bombillo seguridad, pompa, borjas gama media, serie alta(STS)',210.5,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1407',43,'Sustitución cerrojo (LINCE 3940, LINCE 2930, EZCURRA 400 o similar)',169.88,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1408',43,'Sustitución cerrojo (FAC 300, FAC 301, FAC 307 o similar)',160.89,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1409',43,'Sustitución de muelle (Tipo Dorma, Azbe)',197.94,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1410',43,'Mano de obra cerrajería.',57.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1301',44,'Luna pulida de 3 mm.',76.81,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1302',44,'Luna pulida de 4 mm.',88.16,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1303',44,'Luna pulida de 5 mm.',98.20999999999999,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1304',44,'Luna pulida de 6 mm.',107.02,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1305',44,'Luna pulida de 8 mm.',135.98,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1306',44,'Luna pulida de 10 mm.',164.93,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1307',44,'Luna Parsol de 5 mm.',109.55,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1308',44,'Luna Parsol de 6 mm.',124.63,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1309',44,'Luna Parsol de 10 mm.',195.17,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1310',44,'Luna espejo de 3 mm.',98.20999999999999,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1311',44,'Luna espejo 5 mm.',139.79,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1312',44,'Vidrio listral.',75.56,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1313',44,'Vidrio Madras.',201.46,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1314',44,'Vidrio armado.',103.88,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1315',44,'Canto pulido hasta 6 mm.',7.93,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1316',44,'Canto pulido mas de 6 mm.',13.23,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1317',44,'Bisel hasta 6 mm.',15.97,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1318',44,'Bisel mas de 6 mm.',18.64,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1319',44,'Taladro hasta 10 mm.',8.01,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1320',44,'Taladro hasta 40 mm.',22.22,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('1321',44,'Mano de obra cristalería.',57.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('601',45,'Mano de obra de electricidad',43.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('602',45,'Revisión instalación eléctrica',70.76,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('603',45,'Sustitución de interruptor, enchufe o timbre serie SIMON31 o similar.',55.49,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('604',45,'Sustitución pulsador con indicador luminoso serie SIMON31 o similar.',70.33,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('605',45,'Sustitución de automático de escalera T20 o similar.',97.48,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('606',45,'Sustitución de automático de escalera T11 o similar.',124.33,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('607',45,'Sustitución de diferencial hasta 2x40A sensibilidad 30mA.',91.31,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('608',45,'Sustitución de diferencial de 2x63A sensibilidad 30mA.',375.06,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('609',45,'Sustitución de diferencial de 4x40A sensibilidad 300mA.',246.41,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('610',45,'Sustitución de diferencial de 4x63A sensibilidad 300mA.',403.44,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('611',45,'Sustitución de diferencial hasta 4x40A sensibilidad 30mA.',284.24,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('612',45,'Sustitución de magnetotérmico 2x25A.',69.5,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('613',45,'Sustitución de magnetotérmico 2x40A.',76.19,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('614',45,'Sustitución de magnetotérmico 2x50A.',88.17,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('615',45,'Sustitución de magnetotérmico 4x25A.',142.17,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('616',45,'Sustitución de magnetotérmico 4x40A.',166.63,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('617',45,'Sustitución de magnetotérmico 4x50A.',280.97,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('618',45,'Cambio de línea hasta 2,5 mm2',8.4,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('619',45,'Cambio de línea de 4 mm2',8.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('620',45,'Cambio de línea hasta 6 mm2',9.25,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('101',46,'Localización de avería incluso apertura.',63.19,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('102',46,'Desmontaje y montaje de aparato sanitario.',82.96,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('103',46,'Desmontaje y montaje de aparato sanitario con otra reparación.',55.84,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('104',46,'Desmontaje de aparato sanitario con otra reparación.',18.59,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('105',46,'Únicamente desmontaje de aparato sanitario.',43.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('106',46,'Únicamente montaje aparato sanitario.',49.64,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('107',46,'Únicamente sustitución de latiguillo.',42.14,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('108',46,'Sustitución de latiguillo con otra reparación.',24.54,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('109',46,'Únicamente sustitución de válvula de desagüe.',74.78,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('110',46,'Sustitución de válvula y rebosadero de bañera.',109.17,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('111',46,'Sustitución de válvula de desagüe con otra reparación.',59.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('112',46,'Sustitución de sifón.',70.71,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('113',46,'Sustitución de llave de escuadra.',53.9,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('114',46,'Sustitución de llave de corte.',76.42,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('115',46,'Cambio de manguetón de plomo o P.V.C.',310.16,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('116',46,'Reparación de manguetón.',88.7,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('117',46,'Sustitución de bote sifónico normal.',223.3,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('118',46,'Reparación de bote sifónico.',93.07,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('119',46,'Tubería de distribución hasta 1" y hasta 1ml.',122.81,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('120',46,'Tubería de distribución desde 1"1/4 hasta 2" y hasta 1ml.',264.47,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('121',46,'Tubería de distribución hasta 1" y hasta 3ml.',210.89,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('122',46,'Tubería de distribución desde 1"1/4 hasta 2" y hasta 3ml.',447.28,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('123',46,'Reparación de tubería de distribución sin sustitución.',79.15,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('124',46,'Sustitución hasta 1ml de desagüe de PVC de 40mm de Ø.',122.81,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('125',46,'Sustitución hasta 3ml de desagüe de PVC de 40mm de Ø.',151.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('126',46,'Sustitución hasta 1ml de desagüe de plomo.',99.24,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('127',46,'Sustitución hasta 3ml de desagüe de plomo.',161.26,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('128',46,'Sustitución hasta 1,5ml de desagüe de fregadero y lavadora.',163.74,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('129',46,'Sustitución hasta 3ml de desagüe fregadero y lavadora.',248.13,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('130',46,'Reparación de desagüe sin sustitución.',85.59,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('131',46,'Sustitución de injerto sencillo, incluso 1ml bajante.',290.67,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('132',46,'Sustitución de injerto sencillo, incluso 3ml bajante.',360.91,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('133',46,'Sustitución de injerto doble, incluso 1ml de bajante.',359.78,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('134',46,'Sustitución de injerto doble, incluso 3ml de bajante.',405.34,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('135',46,'Sustitución de bajante de pluviales, hasata 1ml.',119.26,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('136',46,'Sustitución de bajante de pluviales, tramo hasta 3 ml.',238.56,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('137',46,'Sustitución de bajante de fecales o mixta, tramo hasta 1ml.',136.46,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('138',46,'Sustitución de bajante de fecales o mixta, tramo hasta 3ml.',272.93,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('139',46,'Reparación  de bajante sin sustitución.',88.7,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('140',46,'Cambio de codo con banjante.',138.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('141',46,'Reparación de unión en bajante.',119.08,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('142',46,'Apertura de cala.',54.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('143',46,'Reparación de tubería con de gebo tapaporos de 1/2".',102.84,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('144',46,'Reparación de tubería con de gebo tapaporos de 3/4".',103.49,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('145',46,'Reparación de tubería con de gebo tapaporos de 1" Y 1/4.',111.25,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('146',46,'Reparación de tubería con gebo tapaporos de 1" Y 1/2.',113.57,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('147',46,'Reparación de tubería con 2 gebos y tramo de tuberia de 1/2".',131.5,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('148',46,'Reparación de tubería con 2 gebos y tramo de tuberia 3/4".',134.01,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('149',46,'Cambio de llave de regulación de radiador.',72.89,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('150',46,'Cambio de detentor.',58.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('151',46,'Contador de agua fría de 3/4 (20mm)',70.7,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('152',46,'Instalación de contador',46.76,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('153',46,'Suministro contador agua fría 1/2 (13mm)',44.29,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('154',46,'Mano de obra de fontanería.',43.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('701',47,'Pintura al temple liso de 1 a 7 m2',89.90000000000001,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('702',47,'Pintura al temple liso de 7 a 15 m2',108.21,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('703',47,'Pintura al temple liso m2 adicional.',5.18,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('704',47,'Pintura al temple picado de 1 a 7 m2',121.46,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('705',47,'Pintura al temple picado de 7 a 15 m2',173.68,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('706',47,'Pintura al temple picado m2 adicional.',7.84,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('707',47,'Pintura al temple gotele de 1 a 7 m2',121.46,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('708',47,'Pintura al temple gotele de 7 a 15 m2',137.98,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('709',47,'Pintura al temple gotele m2 adicional.',7.84,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('710',47,'Temple picado plastificado de 1 a 7 m2',179.59,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('711',47,'Temple picado plastificado de 7 a 15 m2',201.27,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('712',47,'Temple picado plastificado m2 adicional',11.26,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('713',47,'Temple gotele plastificado de 1 a 7 m2',151.03,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('714',47,'Temple gotele plastificado de 7 a 15 m2',173.68,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('715',47,'Temple gotele plastificado m2 adicional',10.48,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('716',47,'Pintura plastica lisa de 1 a 7 m2',114.97,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('717',47,'Pintura plastica lisa de 7 a 15 m2',145.04,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('718',47,'Pintura plastica lisa m2 adicional.',9.19,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('719',47,'Pasta rayada de 1 a 7 m2',114.97,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('720',47,'Pasta rayada de 7 a 15 m2',145.04,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('721',47,'Pasta rayada m2 adicional',9.19,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('722',47,'Pintura al esmalte de 1 a 7 m2',152.1,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('723',47,'Pintura al esmalte de 7 a 15 m2',243.34,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('724',47,'Pintura al esmalte m2 adicional.',18.34,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('725',47,'Mano de obra de pintor',43.83,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('2101',48,'Desplazamiento de cuadrilla',108.15,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('2102',48,'Mano de obra de cuadrilla poceria.',108.15,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('2103',48,'Desplazamiento de equipo para inspección con cámara de TV.',125,9);
INSERT INTO articulos(codigoBarras,grupoArticuloId,nombre,precioUnitario,unidadId) VALUES ('2104',48,'Mano de obra para revisión de instalación con cámara.',125,9);

/*LINEAS*/

INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,93,12.75);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,94,11.72);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,95,38.25);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,96,22.37);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,97,18.58);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,98,22.35);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,99,24.19);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,100,41.73);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,101,40.08);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,102,46.94);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,103,26.75);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,104,25.06);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,105,34.53);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,106,25.28);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,107,41.73);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,108,41.73);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,109,73.06);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,110,5.52);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,111,8.52);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,112,7.01);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,113,6.01);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,114,15.03);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,115,7.51);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,116,26.04);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,117,19.42);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,118,15.03);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,119,10.51);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,120,20.52);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,251,73);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,252,53);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,253,73);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (1,254,53);


INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,121,55);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,122,49.15);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,123,70.86);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,124,101.51);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,125,106.7);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,126,93.45999999999999);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,127,75.42);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,128,71.42);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,129,90);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,130,25.91);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,226,30.59);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,227,36.69);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,228,1.5);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,229,40.51);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,230,47.28);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,231,2.32);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,232,40.51);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,233,47.28);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,234,2.31);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,235,47.65);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,236,53.01);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,237,2.52);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,238,47.65);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,239,53.01);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,240,2.52);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,241,35.3);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,242,42.88);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,243,2.16);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,244,41.67);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,245,47.28);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,246,2.31);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,257,51.47);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,248,69.33);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,259,4.22);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (2,250,20.52);

INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,131,34.42);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,132,39.51);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,133,44);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,134,47.95);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,135,60.93);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,136,73.90000000000001);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,137,49.08);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,138,55.85);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,139,87.45999999999999);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,140,44);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,141,63.24);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,142,33.86);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,143,90.27);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,144,46.55);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,145,3.56);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,146,5.92);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,147,7.16);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,148,8.35);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,149,3.58);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,150,9.949999999999999);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (3,151,24.96);

INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,152,20);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,153,34.88);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,154,25.41);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,155,30.72);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,156,45.94);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,157,55.51);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,158,40.77);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,159,167.46);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,160,110.02);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,161,139.51);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,162,126.91);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,163,31.03);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,164,34.02);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,165,39.37);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,166,63.48);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,167,74.4);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,168,139.2);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,169,3.75);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,170,3.94);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (4,171,4.13);

INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,172,18.06);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,173,18.06);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,174,13.07);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,175,6.63);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,176,18.06);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,177,18.06);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,178,18.06);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,179,7.85);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,180,24.14);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,181,31.99);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,182,19.31);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,183,22.32);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,184,17.5);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,185,24.75);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,186,82.6);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,187,28.38);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,188,73.41);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,189,32.59);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,190,37.85);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,191,101.71);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,192,64.6);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,193,172.04);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,194,25.36);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,195,27.07);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,196,37.36);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,197,30.82);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,198,50.47);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,199,44.52);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,200,88.14);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,201,25.36);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,202,78.8);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,203,113.82);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,204,87.55);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,205,127.82);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,206,43.78);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,207,59.16);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,208,52.53);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,209,98.07);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,210,28.38);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,211,51.02);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,212,42.26);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,213,18.06);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,214,27.69);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,215,28.11);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,216,33.01);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,217,34.48);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,218,46.3);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,219,47.18);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,220,22.38);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,221,22.38);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,222,0);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,223,0);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,224,0);
INSERT INTO tarifas_lineas(tarifaId,articuloId,precioUnitario) VALUES (5,225,17.96);

INSERT INTO tarifas_lineas (tarifaId, articuloId, precioUnitario) 
(SELECT 6 AS tarifaId, articuloId, precioUnitario FROM articulos WHERE grupoArticuloId = 42 OR grupoArticuloId = 43 OR grupoArticuloId = 44 OR 
grupoArticuloId = 45 OR grupoArticuloId = 46 OR grupoArticuloId = 47 OR grupoArticuloId = 48);












