CREATE TABLE IF NOT EXISTS temp_articulos(
   codReparacion    VARCHAR(255) NOT NULL PRIMARY KEY
  ,descripcion      VARCHAR(255) NOT NULL
  ,cliente_tarifa_1 NUMERIC(6,2) NOT NULL
);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('101','Localización de avería incluso apertura.',63.19);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('102','Desmontaje y montaje de aparato sanitario.',82.96);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('103','Desmontaje y montaje de aparato sanitario con otra reparación.',55.84);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('104','Desmontaje de aparato sanitario con otra reparación.',18.59);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('105','Únicamente desmontaje de aparato sanitario.',43.83);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('106','Únicamente montaje aparato sanitario.',49.64);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('107','Únicamente sustitución de latiguillo.',42.14);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('108','Sustitución de latiguillo con otra reparación.',24.54);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('109','Únicamente sustitución de válvula de desagüe.',74.78);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('110','Sustitución de válvula y rebosadero de bañera.',109.17);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('111','Sustitución de válvula de desagüe con otra reparación.',59.83);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('112','Sustitución de sifón.',70.71);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('113','Sustitución de llave de escuadra.',53.90);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('114','Sustitución de llave de corte.',76.42);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('115','Cambio de manguetón de plomo o P.V.C.',310.16);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('116','Reparación de manguetón.',88.70);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('117','Sustitución de bote sifónico normal.',223.30);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('118','Reparación de bote sifónico.',93.07);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('119','Tubería de distribución hasta 1" y hasta 1ml.',122.81);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('120','Tubería de distribución desde 1"1/4 hasta 2" y hasta 1ml.',264.47);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('121','Tubería de distribución hasta 1" y hasta 3ml.',210.89);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('122','Tubería de distribución desde 1"1/4 hasta 2" y hasta 3ml.',447.28);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('123','Reparación de tubería de distribución sin sustitución.',79.15);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('124','Sustitución hasta 1ml de desagüe de PVC de 40mm de Ø.',122.81);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('125','Sustitución hasta 3ml de desagüe de PVC de 40mm de Ø.',151.83);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('126','Sustitución hasta 1ml de desagüe de plomo.',99.24);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('127','Sustitución hasta 3ml de desagüe de plomo.',161.26);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('128','Sustitución hasta 1,5ml de desagüe de fregadero y lavadora.',163.74);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('129','Sustitución hasta 3ml de desagüe fregadero y lavadora.',248.13);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('130','Reparación de desagüe sin sustitución.',85.59);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('131','Sustitución de injerto sencillo, incluso 1ml bajante.',290.67);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('132','Sustitución de injerto sencillo, incluso 3ml bajante.',360.91);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('133','Sustitución de injerto doble, incluso 1ml de bajante.',359.78);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('134','Sustitución de injerto doble, incluso 3ml de bajante.',405.34);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('135','Sustitución de bajante de pluviales, hasata 1ml.',119.26);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('136','Sustitución de bajante de pluviales, tramo hasta 3 ml.',238.56);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('137','Sustitución de bajante de fecales o mixta, tramo hasta 1ml.',136.46);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('138','Sustitución de bajante de fecales o mixta, tramo hasta 3ml.',272.93);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('139','Reparación  de bajante sin sustitución.',88.70);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('140','Cambio de codo con banjante.',138.83);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('141','Reparación de unión en bajante.',119.08);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('142','Apertura de cala.',54.83);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('143','Reparación de tubería con de gebo tapaporos de 1/2".',102.84);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('144','Reparación de tubería con de gebo tapaporos de 3/4".',103.49);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('145','Reparación de tubería con de gebo tapaporos de 1" Y 1/4.',111.25);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('146','Reparación de tubería con gebo tapaporos de 1" Y 1/2.',113.57);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('147','Reparación de tubería con 2 gebos y tramo de tuberia de 1/2".',131.50);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('148','Reparación de tubería con 2 gebos y tramo de tuberia 3/4".',134.01);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('149','Cambio de llave de regulación de radiador.',72.89);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('150','Cambio de detentor.',58.83);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('151','Contador de agua fría de 3/4 (20mm)',70.70);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('152','Instalación de contador',46.76);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('153','Suministro contador agua fría 1/2 (13mm)',44.29);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('154','Mano de obra de fontanería.',43.83);
INSERT INTO temp_articulos(codReparacion,descripcion,cliente_tarifa_1) VALUES ('155','Desplazamiento',29.00);
